---
name: Unit tests
"on": push
permissions:
  checks: write
jobs:
  run-unit-tests:
    name: Run vitest unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run vitest
        run: pnpm test:unit
